# Generated by Django 5.1 on 2024-11-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetRange',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
    ]
