# Generated by Django 5.1 on 2024-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_delete_budgetrange_remove_activity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
