# Generated by Django 5.1 on 2024-11-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_activity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybudgetrange',
            name='high_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailybudgetrange',
            name='low_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailybudgetrange',
            name='medium_food',
            field=models.IntegerField(default=0),
        ),
    ]
