# Generated by Django 5.1 on 2024-11-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_dailybudgetrange_high_food_dailybudgetrange_low_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybudgetrange',
            name='high_food',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailybudgetrange',
            name='low_food',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailybudgetrange',
            name='medium_food',
            field=models.FloatField(),
        ),
    ]
