# Generated by Django 5.1 on 2024-11-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_remove_dailybudgetrange_high_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
    ]
