# Generated by Django 5.1 on 2024-11-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0007_remove_location_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Cultural and Heritage Tours', 'Cultural and Heritage Tours'), ('Nature and Wildlife Tours', 'Nature and Wildlife Tours'), ('Beach and Coastal Tours', 'Beach and Coastal Tours'), ('Adventure Tours', 'Adventure Tours'), ('General', 'General')], max_length=100),
        ),
    ]
