# Generated by Django 5.1 on 2024-11-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0008_activity_activity_rank_alter_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price_range',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
