# Generated by Django 5.1 on 2024-11-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0009_activity_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcost',
            name='daily_budget_range',
        ),
        migrations.DeleteModel(
            name='DailyBudgetRange',
        ),
        migrations.DeleteModel(
            name='FoodCost',
        ),
    ]
