# Generated by Django 5.1 on 2024-11-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0010_remove_foodcost_daily_budget_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
